### PR TITLE
feat: add regex path transformation

### LINKED ISSUE #66: Support pure ESM with TypeScript
I'm migrating a TypeScript project to output pure ESM. As part of that effort, I need to update every import which was previously extensionless, to specify a ".js" extension (even though the file in the source directory has a ".ts" extension). Like this:

```TypeScript
// old way
import aThing from '../a/module';

// new way
import aThing from '../a/module.js';
```

It seems like unimported is unable to determine that `../a/module.js` should be resolved to `../a/module.ts` and so it reports almost all files as being unimported.

I've been referencing [this guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) for the migration to pure ESM.

### PR DESCRIPTION
**Pull request by chasingmaxwell**
This is useful for TypeScript projects outputing pure ESM.

See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm.

Closes #66.

### CODE REVIEW

**Comment by chasingmaxwell** [comment]
Looks like the PR checks are failing in the same way the main branch on my local did. I think it's an issue with the TypeScript version range. When I pin it to the exact version specified in package.json it passes. I can work on fixing that as part of my PR, or if you would prefer I could fix in a separate branch/PR since it doesn't have anything to do with my pathTransforms change.

**Comment by chasingmaxwell** [comment]
Here's a PR to fix the test failures I was seeing on the main branch: https://github.com/smeijer/unimported/pull/69

**Comment by Zaram22** [comment]
Support remix

**Comment by Zaram22** [comment]
#69

**Comment by AnotherHermit** [comment]
Hi, is there anything stopping this from being merged? We just recently migrated our typescript codebase to ESM and just noticed now that this tool had some issues with the new file imports. Seems like this PR fixes that issue so it would be amazing to get it merged

**Comment by Onimishra** [comment]
Is there any progress on this PR?

**Comment by chasingmaxwell** [comment]
As far as I know this is still good to go. There are no conflicts with the base branch. It just needs to be reviewed and merged.

**Review by smeijer — APPROVED** [review]

**Comment by smeijer** [comment]
Thanks! I've merged it. Sorry it took me so long. 

I've also added you as a collaborator on the project. Please continue to make PRs as you feel the need. You can now make your branches directly on the repo rather than your fork if you want.

Thanks again! Much appreciated. :heart:

**Pull request merged**
