### PR TITLE
Update Node support to v16, CI to 18

### PR DESCRIPTION
**Pull request by ryanwilsonperkin**
Node v14 is presenting some issues for https://github.com/smeijer/unimported/pull/181
The new version of the `@typescript-eslint` library that `unimported` relies on makes use of features like the conditional assignment operator which wasn't added until Node v15.

Given the LTS support schedule, it seems reasonable to drop the explicit support for Node v14 that's used in CI and update to v16 for support(still out of date, but less so) and v18 for testing (LTS support window).

### CODE REVIEW

**Comment by smeijer** [comment]
Thanks! Tho, node 16 is EOL as well. Can you bump it to Node 18 instead?

**Comment by smeijer** [comment]
If you want, we can also take a stab at matrix testing and running tests against both 18 and 20. That way we could recommend 20, but ensure compatibility with 18.

**Comment by ryanwilsonperkin** [comment]
Could I suggest supporting engines >=16 but testing on 18 & 20?
Benefit being that it's not currently using any >=18 exclusive libraries, and can thus still technically support v16 apps without issuing warnings, or failing to install on strict configs. I've got at least one v16 app that hasn't yet upgraded that I'd like to be able to use this library against in the meantime.

**Comment by smeijer** [comment]
That works for me. I was mostly concerned about he github workflow. I think we should run it on a supported version. I'm not going to forbid a consumer to use the lib in their v16 env when we can reasonably support it. 🙂

**Comment by smeijer** [comment]
Thank you! 

FYI, this repo qualifies for [hacktoberfest](https://hacktoberfest.com) contributions if that's your thing.

**Pull request merged**
