### PR TITLE
feat: Ignore Unimported Files Mentioned in .gitignore

### PR DESCRIPTION
**Pull request by Fritsch-Tech**
#### Changes Made

This pull request introduces the option to ignore unimported files listed in the `.gitignore` file, addressing the issue raised in  #173. The handling of the `.gitignore` is managed through [ignore](https://www.npmjs.com/package/ignore), as per your recommendation.

This functionality can be enabled via the `respectGitignore` setting, which is set to true by default.

#### Purpose

The addition of this feature enhances the tool's usability by allowing it to seamlessly work with projects where certain files are intentionally excluded via `.gitignore`. 

#### To-Do

- Add information to the README regarding this new feature.
- Implement appropriate tests to ensure the functionality is robust.

Before proceeding with the implementation of these tasks, I wanted to gather your feedback on the current changes. Your input is highly valuable.

Thank you for your time and consideration.

### CODE REVIEW

**Comment by smeijer** [comment]
Thanks! The implementation looks good to me. If you could add those tests you mentioned and a quick line in the readme, that'd be great.

**Comment by Fritsch-Tech** [comment]
Tests and a mention in the README are both added now.

**Review by smeijer — APPROVED** [review]
Thank you!

**Comment by smeijer** [comment]
Thanks! This is great 

FYI, this repo qualifies for [hacktoberfest](https://hacktoberfest.com) contributions if that's your thing.

I've also added you as a collaborator on the project. Please feel free to continue to make PRs as you feel the need. You can now make your branches directly on the repo rather than your fork if you want.

Thanks again! Much appreciated. :heart:

**Comment by smeijer** [comment]
@all-contributors please add @Fritsch-Tech for code, test

**Pull request merged**
