### PR TITLE
feat: add `--fix` flag for removing unused files and dependencies

### PR DESCRIPTION
**Pull request by tomfa**
Adds a `--fix` flag for removing unused files and dependencies, ref #138

### CODE REVIEW

**Comment by smeijer** [comment]
Thanks! This is a great addition. Unfortunately, the tests fail on Windows. Can you look into that?

**Comment by tomfa** [comment]
I suspect latest commit will fix Windows tests.

**Comment by tomfa** [comment]
Tell me if there's anything I can do to help move this forward

**Review by smeijer — APPROVED** [review]

**Comment by smeijer** [comment]
This is good to go! Thanks so much.

**Pull request merged**
